default_stages: [ commit, push ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: detect-private-key
      # - id: no-commit-to-branch

  - repo: https://github.com/siderolabs/conform
    rev: v0.1.0-alpha.26
    hooks:
      - id: conform
        stages: [ commit-msg ]

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [ '--check' ]
        pass_filenames: false
      - id: clippy
        args: [ '--', '-A', 'clippy::derive_partial_eq_without_eq' ]
